"""Hand-authored card entries whose name starts with 'g' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import gaddock_teeg  # noqa: F401
from . import galadhrim_ambush  # noqa: F401
from . import galazeth_prismari  # noqa: F401
from . import galvanic_relay  # noqa: F401
from . import gamble  # noqa: F401
from . import gandalf_the_white  # noqa: F401
from . import garnet_princess_of_alexandria  # noqa: F401
from . import garruk_s_uprising  # noqa: F401
from . import gauntlets_of_chaos  # noqa: F401
from . import geistwave  # noqa: F401
from . import generous_gift  # noqa: F401
from . import ghost_quarter  # noqa: F401
from . import ghostfire_slice  # noqa: F401
from . import ghoulish_impetus  # noqa: F401
from . import gift_of_immortality  # noqa: F401
from . import gifts_ungiven  # noqa: F401
from . import giggling_skitterspike  # noqa: F401
from . import gilded_drake  # noqa: F401
from . import gisela_blade_of_goldnight  # noqa: F401
from . import gitaxian_probe  # noqa: F401
from . import giver_of_runes  # noqa: F401
from . import glarb_calamity_s_augur  # noqa: F401
from . import gliding_licid  # noqa: F401
from . import glint_horn_buccaneer  # noqa: F401
from . import glissa_herald_of_predation  # noqa: F401
from . import glissa_sunslayer  # noqa: F401
from . import glowing_one  # noqa: F401
from . import go_for_the_throat  # noqa: F401
from . import goblin_engineer  # noqa: F401
from . import goblin_matron  # noqa: F401
from . import goblin_rabblemaster  # noqa: F401
from . import goblin_recruiter  # noqa: F401
from . import goldspan_dragon  # noqa: F401
from . import gollum_obsessed_stalker  # noqa: F401
from . import gorma_the_gullet  # noqa: F401
from . import grafted_exoskeleton  # noqa: F401
from . import gratuitous_violence  # noqa: F401
from . import grave_venerations  # noqa: F401
from . import greater_realm_of_preservation  # noqa: F401
from . import greenwarden_of_murasa  # noqa: F401
from . import grim_hireling  # noqa: F401
from . import grinding_station  # noqa: F401
from . import guardian_of_faith  # noqa: F401
from . import guardian_project  # noqa: F401
from . import guardian_scalelord  # noqa: F401
from . import guardian_sunmare  # noqa: F401
from . import gyome_master_chef  # noqa: F401
