"""Hand-authored card entries whose name starts with 'p' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import pact_of_negation  # noqa: F401
from . import painful_truths  # noqa: F401
from . import paradigm_shift  # noqa: F401
from . import parallax_wave  # noqa: F401
from . import parallel_lives  # noqa: F401
from . import parasitic_impetus  # noqa: F401
from . import path_to_exile  # noqa: F401
from . import pathbreaker_ibex  # noqa: F401
from . import patrolling_peacemaker  # noqa: F401
from . import pawn_of_ulamog  # noqa: F401
from . import pearl_ear_imperial_advisor  # noqa: F401
from . import peer_into_the_abyss  # noqa: F401
from . import pemmin_s_aura  # noqa: F401
from . import penance  # noqa: F401
from . import pentagram_of_the_ages  # noqa: F401
from . import peregrin_took  # noqa: F401
from . import perplexing_chimera  # noqa: F401
from . import perplexing_test  # noqa: F401
from . import pest_infestation  # noqa: F401
from . import phantasmal_image  # noqa: F401
from . import phyrexian_incubator  # noqa: F401
from . import phyrexian_metamorph  # noqa: F401
from . import phyrexian_revoker  # noqa: F401
from . import pilgrim_of_justice  # noqa: F401
from . import pilgrim_of_virtue  # noqa: F401
from . import pithing_needle  # noqa: F401
from . import plargg_and_nassari  # noqa: F401
from . import play_with_fire  # noqa: F401
from . import plumb_the_forbidden  # noqa: F401
from . import poison_the_cup  # noqa: F401
from . import polymorph  # noqa: F401
from . import polyraptor  # noqa: F401
from . import ponder  # noqa: F401
from . import pongify  # noqa: F401
from . import possibility_storm  # noqa: F401
from . import power_artifact  # noqa: F401
from . import powerbalance  # noqa: F401
from . import praetor_s_grasp  # noqa: F401
from . import price_of_glory  # noqa: F401
from . import priest_of_forgotten_gods  # noqa: F401
from . import primal_vigor  # noqa: F401
from . import primary_research  # noqa: F401
from . import primo_the_unbounded  # noqa: F401
from . import prismari_pianist  # noqa: F401
from . import prismatic_circle  # noqa: F401
from . import prismatic_ward  # noqa: F401
from . import prize_pig  # noqa: F401
from . import professor_onyx  # noqa: F401
from . import progenitor_exarch  # noqa: F401
from . import promise_of_loyalty  # noqa: F401
from . import protean_hulk  # noqa: F401
from . import protective_sphere  # noqa: F401
from . import psychic_transfer  # noqa: F401
from . import puca_s_covenant  # noqa: F401
from . import puppeteer_clique  # noqa: F401
from . import pure_intentions  # noqa: F401
from . import pyrohemia  # noqa: F401
