"""Hand-authored card entries whose name starts with 'd' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import damn  # noqa: F401
from . import damping_sphere  # noqa: F401
from . import dance_of_the_dead  # noqa: F401
from . import dance_with_calamity  # noqa: F401
from . import danny_pink  # noqa: F401
from . import dark_confidant  # noqa: F401
from . import dark_petition  # noqa: F401
from . import darksteel_mutation  # noqa: F401
from . import darksteel_reactor  # noqa: F401
from . import dauntless_dismantler  # noqa: F401
from . import dauthi_voidwalker  # noqa: F401
from . import day_s_undoing  # noqa: F401
from . import daze  # noqa: F401
from . import dazzling_reflection  # noqa: F401
from . import deadeye_navigator  # noqa: F401
from . import deadly_brew  # noqa: F401
from . import deathmist_raptor  # noqa: F401
from . import decimate  # noqa: F401
from . import deepglow_skate  # noqa: F401
from . import defy_death  # noqa: F401
from . import depthshaker_titan  # noqa: F401
from . import deekah_fractal_theorist  # noqa: F401
from . import defense_grid  # noqa: F401
from . import defense_of_the_heart  # noqa: F401
from . import defiler_of_dreams  # noqa: F401
from . import defiler_of_vigor  # noqa: F401
from . import defiling_daemogoth  # noqa: F401
from . import deflecting_palm  # noqa: F401
from . import deflecting_swat  # noqa: F401
from . import delay  # noqa: F401
from . import delney_streetwise_lookout  # noqa: F401
from . import delver_of_secrets  # noqa: F401
from . import demonic_bargain  # noqa: F401
from . import demonic_consultation  # noqa: F401
from . import demonspine_whip  # noqa: F401
from . import derevi_empyrial_tactician  # noqa: F401
from . import descendants_fury  # noqa: F401
from . import desperate_gambit  # noqa: F401
from . import destiny_spinner  # noqa: F401
from . import desynchronization  # noqa: F401
from . import determined_iteration  # noqa: F401
from . import dihada_binder_of_wills  # noqa: F401
from . import dimension_x_pizzasaur  # noqa: F401
from . import dina_essence_brewer  # noqa: F401
from . import dina_soul_steeper  # noqa: F401
from . import dionus_elvish_archdruid  # noqa: F401
from . import dirgur_focusmage  # noqa: F401
from . import disciple_of_bolas  # noqa: F401
from . import dismantling_wave  # noqa: F401
from . import disorienting_choice  # noqa: F401
from . import dispatch  # noqa: F401
from . import display_of_power  # noqa: F401
from . import distant_melody  # noqa: F401
from . import divine_visitation  # noqa: F401
from . import diviner_of_mist  # noqa: F401
from . import djinn_of_infinite_deceits  # noqa: F401
from . import dockside_extortionist  # noqa: F401
from . import dodecapod  # noqa: F401
from . import dominating_licid  # noqa: F401
from . import domri_anarch_of_bolas  # noqa: F401
from . import doomsday  # noqa: F401
from . import doomsday_excruciator  # noqa: F401
from . import doubling_season  # noqa: F401
from . import dragon_s_prey  # noqa: F401
from . import dragonhawk_fate_s_tempest  # noqa: F401
from . import drain_life  # noqa: F401
from . import drakuseth_maw_of_flames  # noqa: F401
from . import dramatic_reversal  # noqa: F401
from . import drana_and_linvala  # noqa: F401
from . import dress_down  # noqa: F401
from . import drumbellower  # noqa: F401
from . import dualcaster_mage  # noqa: F401
from . import dungeon_delver  # noqa: F401
from . import duplicant  # noqa: F401
from . import dusk_urchins  # noqa: F401
from . import dwynen_gilt_leaf_daen  # noqa: F401

from . import deathbringer_regent
from . import dragon_egg
from . import deceptive_frostkite
from . import dread_summons
from . import death_baron
from . import diregraf_colossus
from . import druid_of_purification  # noqa: F401
from . import dancer_s_chakrams  # noqa: F401
from . import demolition_field  # noqa: F401
from . import demon_of_fate_s_design  # noqa: F401
from . import dream_eater  # noqa: F401
from . import deluge_of_doom  # noqa: F401
from . import deadbridge_chant  # noqa: F401
from . import demonic_covenant  # noqa: F401
from . import digsite_engineer  # noqa: F401
from . import dermotaxi  # noqa: F401
from . import disruptor_flute  # noqa: F401
from . import dack_fayden_helping_hand  # noqa: F401
from . import darksteel_angel  # noqa: F401
from . import double_jump_flying_kick  # noqa: F401
from . import double_jump  # noqa: F401
