"""Hand-authored card entries whose name starts with 'f' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import fabled_passage  # noqa: F401
from . import faebloom_trick  # noqa: F401
from . import faeburrow_elder  # noqa: F401
from . import faerie_mastermind  # noqa: F401
from . import fall_from_favor  # noqa: F401
from . import fallen_ideal  # noqa: F401
from . import fandaniel_telophoroi_ascian  # noqa: F401
from . import farewell  # noqa: F401
from . import farmer_cotton  # noqa: F401
from . import fateful_absence  # noqa: F401
from . import fateful_tempest  # noqa: F401
from . import feed_the_swarm  # noqa: F401
from . import fell_the_mighty  # noqa: F401
from . import felothar_the_steadfast  # noqa: F401
from . import feral_appetite  # noqa: F401
from . import ferrafor_young_yew  # noqa: F401
from . import fertile_ground  # noqa: F401
from . import fiery_emancipation  # noqa: F401
from . import fighter_class  # noqa: F401
from . import filth  # noqa: F401
from . import final_act  # noqa: F401
from . import final_fortune  # noqa: F401
from . import final_punishment  # noqa: F401
from . import finale_of_devastation  # noqa: F401
from . import fire_covenant  # noqa: F401
from . import fireblast  # noqa: F401
from . import firemane_commando  # noqa: F401
from . import fisher_s_talent  # noqa: F401
from . import flamescroll_celebrant  # noqa: F401
from . import flanking_licid  # noqa: F401
from . import flare_of_duplication  # noqa: F401
from . import flesh_duplicate  # noqa: F401
from . import flourishing_defenses  # noqa: F401
from . import flowering_of_the_white_tree  # noqa: F401
from . import foggy_swamp_visions  # noqa: F401
from . import formless_genesis  # noqa: F401
from . import forbidden_orchard  # noqa: F401
from . import force_of_negation  # noqa: F401
from . import force_of_vigor  # noqa: F401
from . import force_of_will  # noqa: F401
from . import forging_the_tyrite_sword  # noqa: F401
from . import forgotten_ancient  # noqa: F401
from . import formidable_speaker  # noqa: F401
from . import forsaken_monument  # noqa: F401
from . import fortune_teller_s_talent  # noqa: F401
from . import forum_filibuster  # noqa: F401
from . import fractal_harness  # noqa: F401
from . import frantic_firebolt  # noqa: F401
from . import freyalise_llanowar_s_fury  # noqa: F401
from . import frilled_deathspitter  # noqa: F401
from . import frodo_sauron_s_bane  # noqa: F401
from . import furnace_of_rath  # noqa: F401
from . import furygale_flocking  # noqa: F401
from . import fable_of_the_mirror_breaker

from . import first_responder
from . import forgotten_creation
from . import fear_of_sleep_paralysis  # noqa: F401
from . import florian_voldaren_scion  # noqa: F401
from . import fear_of_burning_alive  # noqa: F401
from . import fomori_vault  # noqa: F401
from . import flayer_of_the_hatebound  # noqa: F401
