"""Hand-authored card entries whose name starts with 't' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import tainted_pact  # noqa: F401
from . import takenuma_abandoned_mire  # noqa: F401
from . import tale_of_katara_and_toph  # noqa: F401
from . import talion_the_kindly_lord  # noqa: F401
from . import talon_gates_of_madara  # noqa: F401
from . import tam_mindful_first_year  # noqa: F401
from . import tanazir_quandrix  # noqa: F401
from . import tangle_wire  # noqa: F401
from . import tangleweave_armor  # noqa: F401
from . import tataru_taru  # noqa: F401
from . import tavern_brawler  # noqa: F401
from . import tear_asunder  # noqa: F401
from . import tectonic_giant  # noqa: F401
from . import teferi_master_of_time  # noqa: F401
from . import teferi_s_protection  # noqa: F401
from . import teferi_s_time_twist  # noqa: F401
from . import teferi_time_raveler  # noqa: F401
from . import tekuthal_inquiry_dominus  # noqa: F401
from . import tempting_licid  # noqa: F401
from . import temur_sabertooth  # noqa: F401
from . import tenacious_dead  # noqa: F401
from . import tenth_district_hero  # noqa: F401
from . import tergrid_god_of_fright  # noqa: F401
from . import tergrid_s_lantern  # noqa: F401
from . import teshar_ancestor_s_apostle  # noqa: F401
from . import tetsuko_umezawa_fugitive  # noqa: F401
from . import tevesh_szat_doom_of_fools  # noqa: F401
from . import tezzeret_the_seeker  # noqa: F401
from . import thassa_s_oracle  # noqa: F401
from . import the_battle_of_bywater  # noqa: F401
from . import the_elder_dragon_war  # noqa: F401
from . import the_goose_mother  # noqa: F401
from . import the_jolly_balloon_man  # noqa: F401
from . import the_master_gallifrey_s_end  # noqa: F401
from . import the_mycosynth_gardens  # noqa: F401
from . import the_one_ring  # noqa: F401
from . import the_reaper_king_no_more  # noqa: F401
from . import the_wandering_emperor  # noqa: F401
from . import the_wise_mothman  # noqa: F401
from . import thickest_in_the_thicket  # noqa: F401
from . import thought_lash  # noqa: F401
from . import thrasios_triton_hero  # noqa: F401
from . import threefold_thunderhulk  # noqa: F401
from . import throne_of_the_god_pharaoh  # noqa: F401
from . import thunderclap_drake  # noqa: F401
from . import thundermane_dragon  # noqa: F401
from . import tibalt_s_trickery  # noqa: F401
from . import tifa_martial_artist  # noqa: F401
from . import time_wipe  # noqa: F401
from . import timely_ward  # noqa: F401
from . import timetwister  # noqa: F401
from . import tinder_wall  # noqa: F401
from . import tireless_provisioner  # noqa: F401
from . import titan_of_industry  # noqa: F401
from . import titanic_brawl  # noqa: F401
from . import tithe_taker  # noqa: F401
from . import tocasia_s_welcome  # noqa: F401
from . import tomik_wielder_of_law  # noqa: F401
from . import too_evil_to_stay_dead  # noqa: F401
from . import tooth_and_nail  # noqa: F401
from . import torbran_thane_of_red_fell  # noqa: F401
from . import torch_breath  # noqa: F401
from . import torch_the_tower  # noqa: F401
from . import torch_the_witness  # noqa: F401
from . import touch_the_spirit_realm  # noqa: F401
from . import toxic_deluge  # noqa: F401
from . import tragic_arrogance  # noqa: F401
from . import transcendent_dragon  # noqa: F401
from . import transforming_flourish  # noqa: F401
from . import transmogrify  # noqa: F401
from . import transmogrifying_licid  # noqa: F401
from . import transmute_artifact  # noqa: F401
from . import trapjaw_tyrant  # noqa: F401
from . import traumatic_revelation  # noqa: F401
from . import treasure_vault  # noqa: F401
from . import tree_of_perdition  # noqa: F401
from . import treebeard_gracious_host  # noqa: F401
from . import trickbind  # noqa: F401
from . import trinisphere  # noqa: F401
from . import trystan_callous_cultivator  # noqa: F401
from . import turn_inside_out  # noqa: F401
from . import turf_war  # noqa: F401
from . import turntimber_symbiosis  # noqa: F401
from . import twinflame  # noqa: F401
from . import twitching_doll  # noqa: F401
from . import tymna_the_weaver  # noqa: F401
from . import tyvar_kell  # noqa: F401

from . import the_odd_acorn_gang

from . import the_beamtown_bullies  # noqa: F401
