"""Hand-authored card entries whose name starts with 'h' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import haazda_shield_mate  # noqa: F401
from . import halvar_god_of_battle  # noqa: F401
from . import hangarback_walker  # noqa: F401
from . import hapatra_vizier_of_poisons  # noqa: F401
from . import harmonic_prodigy  # noqa: F401
from . import harold_and_bob_first_numens  # noqa: F401
from . import harsh_mentor  # noqa: F401
from . import hateful_eidolon  # noqa: F401
from . import haunted_one  # noqa: F401
from . import haunting_voyage  # noqa: F401
from . import haywire_mite  # noqa: F401
from . import heat_shimmer  # noqa: F401
from . import hedge_whisperer  # noqa: F401
from . import hedron_field_purists  # noqa: F401
from . import helicarrier_strike  # noqa: F401
from . import heliod_sun_crowned  # noqa: F401
from . import helm_of_awakening  # noqa: F401
from . import helm_of_obedience  # noqa: F401
from . import helm_of_the_host  # noqa: F401
from . import herald_of_amity  # noqa: F401
from . import hermit_druid  # noqa: F401
from . import high_perfect_morcant  # noqa: F401
from . import hoarding_broodlord  # noqa: F401
from . import hofri_ghostforge  # noqa: F401
from . import homeward_path  # noqa: F401
from . import honorable_passage  # noqa: F401
from . import hope_of_ghirapur  # noqa: F401
from . import horde_of_notions  # noqa: F401
from . import horizon_of_progress  # noqa: F401
from . import hostility  # noqa: F401
from . import hullbreaker_horror  # noqa: F401
from . import humility  # noqa: F401
from . import hunted_by_the_family  # noqa: F401
from . import hydroelectric_specimen  # noqa: F401
from . import hydroid_krasis  # noqa: F401
