"""Hand-authored card entries whose name starts with 'r' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import radiant_lotus  # noqa: F401
from . import raffine_s_guidance  # noqa: F401
from . import ragavan_nimble_pilferer  # noqa: F401
from . import raggadragga_goreguts_boss  # noqa: F401
from . import raging_ravine  # noqa: F401
from . import rain_of_filth  # noqa: F401
from . import ral_monsoon_mage  # noqa: F401
from . import ram_through  # noqa: F401
from . import ramos_dragon_engine  # noqa: F401
from . import ranger_captain_of_eos  # noqa: F401
from . import rapacious_guest  # noqa: F401
from . import raph_leo_sibling_rivals  # noqa: F401
from . import raphael_ninja_destroyer  # noqa: F401
from . import rapid_augmenter  # noqa: F401
from . import rapid_hybridization  # noqa: F401
from . import reality_scramble  # noqa: F401
from . import reality_shift  # noqa: F401
from . import realmwalker  # noqa: F401
from . import reanimate  # noqa: F401
from . import recruiter_of_the_guard  # noqa: F401
from . import red_hulk  # noqa: F401
from . import redoubled_stormsinger  # noqa: F401
from . import reiterate  # noqa: F401
from . import relic_retriever  # noqa: F401
from . import relic_seeker  # noqa: F401
from . import rem_karolus_stalwart_slayer  # noqa: F401
from . import renegade_bull  # noqa: F401
from . import renewed_faith  # noqa: F401
from . import resculpt  # noqa: F401
from . import resourceful_defense  # noqa: F401
from . import rest_in_peace  # noqa: F401
from . import restless_cottage  # noqa: F401
from . import restless_spire  # noqa: F401
from . import return_of_the_wildspeaker  # noqa: F401
from . import return_the_favor  # noqa: F401
from . import reverse_damage  # noqa: F401
from . import revitalizing_repast  # noqa: F401
from . import rhonas_s_monument  # noqa: F401
from . import rhystic_circle  # noqa: F401
from . import rhystic_study  # noqa: F401
from . import ribtruss_roaster  # noqa: F401
from . import riftstone_portal  # noqa: F401
from . import righteous_aura  # noqa: F401
from . import rings_of_brighthearth  # noqa: F401
from . import rionya_fire_dancer  # noqa: F401
from . import riot_control  # noqa: F401
from . import ripples_of_potential  # noqa: F401
from . import rise_from_the_grave  # noqa: F401
from . import risen_reef  # noqa: F401
from . import rishkar_peema_renegade  # noqa: F401
from . import rite_of_flame  # noqa: F401
from . import roaming_throne  # noqa: F401
from . import roaring_earth  # noqa: F401
from . import robe_of_stars  # noqa: F401
from . import rogue_s_gloves  # noqa: F401
from . import rogue_s_passage  # noqa: F401
from . import rootha_mastering_the_moment  # noqa: F401
from . import rootha_mercurial_artist  # noqa: F401
from . import rosie_cotton_of_south_lane  # noqa: F401
from . import rousing_refrain  # noqa: F401
from . import ruination  # noqa: F401
from . import runadi_behemoth_caller  # noqa: F401
from . import runaway_steam_kin  # noqa: F401
from . import rune_of_protection_artifacts  # noqa: F401
from . import rune_of_protection_black  # noqa: F401
from . import rune_of_protection_blue  # noqa: F401
from . import rune_of_protection_green  # noqa: F401
from . import rune_of_protection_lands  # noqa: F401
from . import rune_of_protection_red  # noqa: F401
from . import rune_of_protection_white  # noqa: F401
from . import runic_armasaur  # noqa: F401
from . import reflection_of_kiki_jiki
from . import ripples_of_undeath

from . import rain_of_riches  # noqa: F401
from . import reflections_of_littjara
from . import rot_hulk
from . import razorlash_transmogrant
