"""Hand-authored card entries whose name starts with 'm' (see game/card_registry for the registration mechanism: `register`/`register_family`/`specs_for`)."""
from . import machine_god_s_effigy  # noqa: F401
from . import magda_brazen_outlaw  # noqa: F401
from . import magda_the_hoardmaster  # noqa: F401
from . import malakir_rebirth  # noqa: F401
from . import malcolm_keen_eyed_navigator  # noqa: F401
from . import mana_bloom  # noqa: F401
from . import mana_breach  # noqa: F401
from . import mana_crypt  # noqa: F401
from . import mana_drain  # noqa: F401
from . import mana_geyser  # noqa: F401
from . import mana_reflection  # noqa: F401
from . import mana_vault  # noqa: F401
from . import mana_web  # noqa: F401
from . import manabarbs  # noqa: F401
from . import manaform_hellkite  # noqa: F401
from . import mangara_the_diplomat  # noqa: F401
from . import maralen_of_the_mornsong  # noqa: F401
from . import march_of_otherworldly_light  # noqa: F401
from . import march_of_swirling_mist  # noqa: F401
from . import march_of_the_world_ooze  # noqa: F401
from . import marchesa_dealer_of_death  # noqa: F401
from . import marchesa_the_black_rose  # noqa: F401
from . import mariposa_military_base  # noqa: F401
from . import martial_coup  # noqa: F401
from . import martial_impetus  # noqa: F401
from . import martyr_s_cause  # noqa: F401
from . import mass_of_mysteries  # noqa: F401
from . import massacre_girl_known_killer  # noqa: F401
from . import master_chef  # noqa: F401
from . import master_of_the_hunt  # noqa: F401
from . import masterwork_of_ingenuity  # noqa: F401
from . import mathemagics  # noqa: F401
from . import mayhem_devil  # noqa: F401
from . import mazemind_tome  # noqa: F401
from . import mazirek_kraul_death_priest  # noqa: F401
from . import meek_attack  # noqa: F401
from . import memory_vampire  # noqa: F401
from . import mercenaries  # noqa: F401
from . import merchant_of_venom  # noqa: F401
from . import meren_of_clan_nel_toth  # noqa: F401
from . import meriadoc_brandybuck  # noqa: F401
from . import merry_warden_of_isengard  # noqa: F401
from . import metallic_mimic  # noqa: F401
from . import mezzio_mugger  # noqa: F401
from . import mesmeric_orb  # noqa: F401
from . import midnight_banshee  # noqa: F401
from . import mikaeus_the_unhallowed  # noqa: F401
from . import mind_into_matter  # noqa: F401
from . import mindblade_render  # noqa: F401
from . import mindslaver  # noqa: F401
from . import mirage_mirror  # noqa: F401
from . import mirkwood_bats  # noqa: F401
from . import mirror_mirror  # noqa: F401
from . import mirrormade  # noqa: F401
from . import mirrormind_crown  # noqa: F401
from . import mirrorwing_dragon  # noqa: F401
from . import misdirection  # noqa: F401
from . import misleading_signpost  # noqa: F401
from . import mistveil_plains  # noqa: F401
from . import mizzix_s_mastery  # noqa: F401
from . import mnemonic_betrayal  # noqa: F401
from . import mockingbird  # noqa: F401
from . import modify_memory  # noqa: F401
from . import monstrous_onslaught  # noqa: F401
from . import moon_blessed_cleric  # noqa: F401
from . import moonsilver_key  # noqa: F401
from . import moraug_fury_of_akoum  # noqa: F401
from . import morcant_s_loyalist  # noqa: F401
from . import mortality_spear  # noqa: F401
from . import mother_of_runes  # noqa: F401
from . import motivated_pony  # noqa: F401
from . import mox_diamond  # noqa: F401
from . import moxite_refinery  # noqa: F401
from . import mr_foxglove  # noqa: F401
from . import muddle_the_ever_changing  # noqa: F401
from . import muldrotha_the_gravetide  # noqa: F401
from . import multani_yavimaya_s_avatar  # noqa: F401
from . import murmuration  # noqa: F401
from . import mutiny  # noqa: F401
from . import mycoloth  # noqa: F401
from . import myr_battlesphere  # noqa: F401
from . import mystic_remora  # noqa: F401
from . import mystic_sanctuary  # noqa: F401

from . import maelstrom_pulse

from . import maskwood_nexus
from . import mosswort_bridge
from . import mutilate
from . import midnight_clock  # noqa: F401
from . import moldgraf_monstrosity  # noqa: F401
from . import mobile_garrison  # noqa: F401
from . import mech_hangar  # noqa: F401
from . import mobilizer_mech  # noqa: F401
from . import mutavault  # noqa: F401
from . import mechtitan_core  # noqa: F401
from . import mechtitan  # noqa: F401
from . import mask_of_griselbrand  # noqa: F401
from . import massacre_girl  # noqa: F401
from . import mogis_god_of_slaughter  # noqa: F401
from . import memory_erosion  # noqa: F401
from . import minas_tirith  # noqa: F401
